version: '3.8'
services:
  user_management:
    build:
      context: ./user_management
    ports:
      - "5000:5000"
    networks:
      - service_network
  product_catalog:
    build:
      context: ./product_catalog
    ports:
      - "5001:5001"
    networks:
      - service_network
networks:
  service_network:
    driver: bridge
